name: deploy-prd

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy files to server (sources)
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.STAGE_SERVER_HOST }}
        username: ${{ secrets.STAGE_SERVER_USERNAME }}
        password: ${{ secrets.STAGE_SERVER_PASSWORD }}
        port: ${{ secrets.STAGE_SERVER_PORT }}
        source: "src/*"
        target: "minecraft-webpage/src"

    - name: Deploy files to server (package specs)
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.STAGE_SERVER_HOST }}
        username: ${{ secrets.STAGE_SERVER_USERNAME }}
        password: ${{ secrets.STAGE_SERVER_PASSWORD }}
        port: ${{ secrets.STAGE_SERVER_PORT }}
        source: "package*"
        target: "minecraft-webpage"

    - name: npm install & process restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGE_SERVER_HOST }}
        port: ${{ secrets.STAGE_SERVER_PORT }}
        username: ${{ secrets.STAGE_SERVER_USERNAME }}
        password: ${{ secrets.STAGE_SERVER_PASSWORD }}
        script: | 
          npm --prefix minecraft-webpage install --only=production
          pm2 restart minecraft-webpage/ecosystem.config.js